# Step 1

FROM node:12-alpine as build-step

RUN mkdir /scanhub

WORKDIR /scanhub

COPY package.json /scanhub

#COPY .env.production /scanhub

RUN npm install

COPY . /scanhub

RUN npm run build-dev


# Stage 2

FROM nginx:1.17.1-alpine

COPY --from=build-step /scanhub/build /usr/share/nginx/html
COPY conf.d/default.conf /etc/nginx/conf.d/default.conf